### ISSUE TITLE
restart

### ISSUE THREAD

**Issue by karas220288** [justanormaldev/ps4-pkg-sender#1]
I'm using libreelec. pkg sender works, but reboots after restart

**Comment by karas220288** [comment]
Log from docker

>     at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
module.js:550,
    throw err;,
    ^,
Error: Cannot find module 'lru-cache',
    at Function.Module._resolveFilename (module.js:548:15),
    at Function.Module._load (module.js:475:25),
    at Module.require (module.js:597:17),
    at require (internal/module.js:11:18),
    at Object.<anonymous> (/opt/apps/pkg_sender/node_modules/mustache-express/mustache-express.js:6:16),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3),
